taskcluster:
  adminRoles:
    - github-team:taskcluster/core
  externallyManaged:
    # smoketests create these resources, and also cleans them up, so leave
    # them alone here...
    - "Client=project/taskcluster/smoketest/.*"
    - "Role=project:taskcluster:smoketest:.*"
  grants:
    - grant:
        - auth:create-client:project/taskcluster/smoketest/*
        - auth:create-role:project:taskcluster:smoketest:*
        - auth:delete-client:project/taskcluster/smoketest/*
        - auth:delete-role:project:taskcluster:smoketest:*
        - auth:reset-access-token:project/taskcluster/smoketest/*
        - auth:update-client:project/taskcluster/smoketest/*
        - auth:update-role:project:taskcluster:smoketest:*
        - project:taskcluster:smoketest:*
        - purge-cache:built-in/succeed:smoketest-cache
        - queue:create-task:highest:built-in/*
        - queue:create-task:highest:built-in/fail
        - queue:create-task:highest:built-in/succeed
        - queue:route:index.project.taskcluster.smoketest.*
        - queue:scheduler-id:smoketest
        - secrets:get:project/taskcluster/smoketest/*
        - secrets:set:project/taskcluster/smoketest/*
      to: project:taskcluster:smoketests

    - grant: assume:project:taskcluster:smoketests
      to: github-team:taskcluster/smoketesters

  clients:
    smoketest:
      scopes:
        - assume:project:taskcluster:smoketests
    # Running periodic audits and worker version reports
    audit-reports:
      scopes:
        - "queue:create-task:lowest:*"
        - "queue:scheduler-id:audit"
