# This file defines "grants" of scopes to roles.  Roles can be repeated, and
# scopes will be merged.
#
# This file should be used for general-purpose roles such as parameterized
# roles and global grants.  Grants related to a specific project should be in
# projects.yml, instead.
#
# Available roles to grant to:
#   github-org-admin:<org> -- admins of the given org
#   github-team:<org>/<team> -- members of the given team
#   login-identity:<identity> -- a specfic user (try to avoid this!)
#   repo:github.com/<org>/<repo>:<event> -- see
#      https://docs.taskcluster.net/docs/reference/integrations/github/taskcluster-yml-v1#scopes-and-roles
#
# Each item has:
#   grant: a list of scopes to grant
#   to: a role or list of roles to grant the scopes to

# project-admin:* parameterized role, defining "admin" scopes for a project
- grant:
    # project-specific scopes
    - project:<..>:*

    # project-specific roles
    - assume:project:<..>:*
    - auth:create-role:project:<..>:*
    - auth:delete-role:project:<..>:*
    - auth:update-role:project:<..>:*

    # project-specific clients
    - auth:create-client:project/<..>/*
    - auth:delete-client:project/<..>/*
    - auth:disable-client:project/<..>/*
    - auth:enable-client:project/<..>/*
    - auth:update-client:project/<..>/*
    - auth:reset-access-token:project/<..>/*

    # project-specific taskQueueIds
    - queue:create-task:lowest:proj-<..>/*
    - queue:create-task:very-low:proj-<..>/*
    - queue:create-task:low:proj-<..>/*
    - queue:create-task:medium:proj-<..>/*
    - queue:create-task:high:proj-<..>/*
    - queue:create-task:very-high:proj-<..>/*
    - queue:create-task:highest:proj-<..>/*
    - queue:claim-work:proj-<..>/*

    # project-specific schedulers
    - queue:rerun-task:<..>/*

    # project-specific private artifacts
    - queue:get-artifact:project/<..>/*

    # project-specific hooks
    - assume:hook-id:project-<..>/*
    - auth:create-role:hook-id:project-<..>/*
    - auth:delete-role:hook-id:project-<..>/*
    - auth:update-role:hook-id:project-<..>/*
    - hooks:modify-hook:project-<..>/*
    - hooks:trigger-hook:project-<..>/*

    # project-specific workers
    - assume:worker-id:proj-<..>/*
    - queue:quarantine-worker:proj-<..>/*
    - worker-manager:create-worker:proj-<..>/*
    - worker-manager:remove-worker:proj-<..>/*

    # project-specific index routes
    - index:insert-task:project.<..>.*
    - queue:route:index.project.<..>.*

    # project-specific worker pools and workers
    - worker-manager:manage-worker-pool:proj-<..>/*
    - assume:worker-pool:proj-<..>/*

    # project-specific worker pools secrets
    - secrets:get:worker-pool:proj-<..>/*
    - secrets:set:worker-pool:proj-<..>/*

    # project-specific secrets
    - secrets:get:project/<..>/*
    - secrets:set:project/<..>/*

    # allow all caches, since workers are per-project
    - docker-worker:cache:*
    - generic-worker:cache:*

    # allow purging caches for project worker-pools
    - purge-cache:proj-<..>/*

    # allow use of all providers
    - worker-manager:provider:null-provider
    - worker-manager:provider:community-tc-workers-*
  to: project-admin:*

# repo-admin:* parameterized role, defining administrative scopes over a github repo
- grant:
    - auth:create-role:repo:<..>
    - auth:delete-role:repo:<..>
    - auth:update-role:repo:<..>
    - assume:repo:<..>
  to: repo-admin:*

- grant:
    # support users' creation of clients
    - auth:create-client:<..>/*
    - auth:delete-client:<..>/*
    - auth:update-client:<..>/*
    - auth:reset-access-token:<..>/*
    # grant all users access to scheduler-id `-`, the default, as well as
    # the task-creator default "taskcluster-ui"
    - queue:scheduler-id:-
    - queue:scheduler-id:taskcluster-ui
    - queue:create-task:highest:built-in/fail
    - queue:create-task:highest:built-in/succeed
    - queue:get-artifact:login-identity/<..>/*
  to:
    - login-identity:*

- grant:
    # worker pool implies claiming work
    - "queue:claim-work:<..>"
    # Get any necessary secrets for this worker pool
    - "secrets:get:worker-pool:<..>"
    # Grant permission to use websocktunnel with audience `communitytc` to all
    # workers in all pools
    - "auth:websocktunnel-token:communitytc/*"
  to: worker-pool:*

# Make assume:worker-id:<id> imply queue:worker-id:<id>
- grant: "queue:worker-id:<..>"
  to: "worker-id:*"

# As a temporary measure until we invent a better solution, we allow a number
# of lucky people to rerun, cancel, and schedule all tasks created by
# taskcluster-github, and to create tasks with that schedulerId (e.g., for
# interactive).  Similarly for the `-` and taskcluster-ui schedulerIds, the old
# and new defaults.
- grant:
    - queue:cancel-task:taskcluster-github/*
    - queue:schedule-task:taskcluster-github/*
    - queue:rerun-task:taskcluster-github/*
    - queue:scheduler-id:taskcluster-github

    - queue:cancel-task:-/*
    - queue:schedule-task:-/*
    - queue:rerun-task:-/*

    - queue:cancel-task:taskcluster-ui/*
    - queue:schedule-task:taskcluster-ui/*
    - queue:rerun-task:taskcluster-ui/*

    - notify:email:*
    - notify:irc-channel:*
    - notify:irc-user:*

    # permission to run interactive tsaks
    - queue:get-artifact:private/docker-worker/*
    - queue:get-artifact:private/generic-worker/*
  to:
    # note, specific users are temporary until mozilla org grants permissions
    # to read teams, https://bugzilla.mozilla.org/show_bug.cgi?id=1593632

    # admins
    - github-team:taskcluster/core

    # glandium, for git-cinnabar
    - login-identity:github/1038527|glandium

    # for firefoxreality
    - github-team:MozillaReality/fxr-eng-tc

    # for a few project admins
    - project-admin:fuzzing
    - project-admin:wpt

    # for bugbug, mozci, relman
    - github-team:mozilla/ci-and-quality-tools

    # for releng
    - github-team:taskcluster/releng

# One of these routes is added to each task created in reaction to a GitHub event.
# If such a task in turn creates other tasks, it can add the same route in order to work around
# https://bugzilla.mozilla.org/show_bug.cgi?id=1548781 or
# https://bugzilla.mozilla.org/show_bug.cgi?id=1533235
- grant:
    # Route names match configuration at
    # https://github.com/taskcluster/taskcluster/blob/21f257dc8/services/github/config.yml#L13-L14
    - queue:route:checks
    - queue:route:statuses
  to:
    # Repositories that wish to use this workaround
    - repo:github.com/web-platform-tests/wpt:*

# Allow the taskcluster team to handle the denylist
- grant: notify:manage-denylist
  to: github-team:taskcluster/core

# Make read-only endpoints public by default
- grant:
    - auth:current-scopes
    - auth:expand-scopes
    - auth:get-client:*
    - auth:get-role:*
    - auth:list-clients
    - auth:list-roles
    - github:get-badge:*
    - github:get-repository:*
    - github:latest-status:*
    - github:list-builds
    - hooks:get:*
    - hooks:list-hooks:*
    - hooks:list-last-fires:*
    - hooks:status:*
    - index:find-task:*
    - index:list-namespaces:*
    - index:list-tasks:*
    - purge-cache:all-purge-requests
    - purge-cache:purge-requests:*
    - queue:claimed-list:*
    - queue:create-task:project:none
    - queue:get-artifact:public/*
    - queue:get-provisioner:*
    - queue:get-task:*
    - queue:get-worker-type:*
    - queue:get-worker:*
    - queue:list-artifacts:*
    - queue:list-dependent-tasks:*
    - queue:list-provisioners
    - queue:list-task-group:*
    - queue:list-worker-types:*
    - queue:list-workers:*
    - queue:pending-count:*
    - queue:pending-list:*
    - queue:status:*
    - secrets:list-secrets
    - web:read-pulse
    - worker-manager:get-worker-pool:*
    - worker-manager:get-worker:*
    - worker-manager:list-providers
    - worker-manager:list-worker-pool-errors:*
    - worker-manager:list-worker-pools
    - worker-manager:list-workers:*
  to: anonymous
